### ISSUE TITLE
Bryan wants you to get into the VC

### ISSUE THREAD

**Issue by faillock** [ChristopherJ123/ChristopherJ123.github.io#6]
Just like usual

**Comment by INCOREV34** [comment]
yep (because bryan can,t life without toto) XD

**Comment by faillock** [comment]
> yep (because bryan can,t life without toto) XD

bruh at last you did make a github account :|

**Comment by INCOREV34** [comment]
yo i

**Comment by faillock** [comment]
> yo i

you gae

**Comment by INCOREV34** [comment]
mulai anda :)

**Comment by faillock** [comment]
> mulai anda :)
kenapa kok tiba2 bikin akun github?i

**Comment by INCOREV34** [comment]
buat nyimpen projek alpro pas praktek kuliah nanti

**Comment by faillock** [comment]
oooooooooooooooooooooooo

**Comment by INCOREV34** [comment]
owo

**Comment by faillock** [comment]
OE TOTO
y r u gae

**Comment by ChristopherJ123** [comment]
yu stupid la

**Comment by ChristopherJ123** [comment]
Re-open if issue still persists

**Comment by ChristopherJ123** [comment]
xd

**Comment by faillock** [comment]
No u
